act_dr6_lenslike code from PyPI
joezuntz/cosmosis-standard-library pull request #104
Opened 2023-09-06 13:52 UTC by itrharrison

Rather than including the `act_dr6_lenslike` python code directly, we instead assume it has already been installed (i.e. fro PyPI).

2023-09-06 14:33 UTC, itrharrison commented
Ack. I didn't mean to open this with `joezuntz:main` as the target. I don't think this is appropriate for merging yet as the module install happens from test-PyPI.

2023-09-19 12:36 UTC, itrharrison commented
@joezuntz this should be ready to go now.

2023-09-19 14:38 UTC, joezuntz requested changes

2023-09-19 14:38 UTC, joezuntz commented on .github/workflows/ci.yml
> +        pip install --index-url https://test.pypi.org/simple/ act_dr6_lenslike
This is the test pypi server, not the real one - is that intended?

2023-09-19 14:38 UTC, joezuntz commented on likelihood/act-dr6-lens/act_dr6_lenslike_interface.py
> +        # block[names.data_vector, 'act_dr6_lens_theory'] = bclkk
It's useful to save the theory, though I know that would require changes to the library.  I'll open an issue there.

2023-09-19 14:38 UTC, joezuntz commented on likelihood/act-dr6-lens/act_dr6_lenslike_interface.py
> +    if data_dict['limber']:
Want to make sure this error is raised in the setup function instead of execute.

2023-09-20 10:46 UTC, joezuntz commented on likelihood/act-dr6-lens/act_dr6_lenslike_interface.py
> +    if data_dict['limber']:
Sorry - I think this was ambiguous - I meant the fact that the limber option is not implemented, not the A_lens bit.

2023-09-20 10:46 UTC, joezuntz commented on likelihood/act-dr6-lens/act_dr6_lenslike_interface.py
> +    if data_dict['limber']:
Sorry - I think this was ambiguous - I meant the fact that the limber option is not implemented, not the A_lens bit.

2023-09-25 08:42 UTC, joezuntz requested changes

2023-09-25 08:42 UTC, joezuntz commented on likelihood/act-dr6-lens/module.yaml
> +        type: "[module dir]/data"
I think this is the default not the type, which is str

2023-09-25 08:43 UTC, joezuntz commented
Just one quick change needed.

2023-09-25 09:42 UTC, merged