A_mod suppression of non-linear power
joezuntz/cosmosis-standard-library pull request #142
Opened 2024-10-25 19:49 UTC by ajouellette

This is a very simple module to sample the phenomenological parameter A_mod from Amon & Efstathiou 2022.

2024-10-30 19:47 UTC, joezuntz requested changes
Thanks so much for this! I have three pretty minor requests for changes and then I'd love to merge it.

2024-10-30 19:47 UTC, joezuntz commented on structure/amod/module.yaml
> +attribution: []
Thanks so much for this contribution! You should definitely give yourself credit by adding your name to the attribution list!

2024-10-30 19:47 UTC, joezuntz commented on structure/amod/module.yaml
> +params:
This block should be replaced with:

```
params: {}
```

2024-10-30 19:47 UTC, joezuntz commented on structure/amod/amod.py
> +    assert (block["matter_power_lin", "z"] == block["matter_power_nl", "z"]).all()
Could you replace these with this, just to give some more info to the user:
```
z_same = np.allclose(block["matter_power_lin", "z"], block["matter_power_nl", "z"])
k_same = np.allclose(block["matter_power_lin", "k_h"], block["matter_power_nl", "k_h"])
if not k_same and z_same:
    raise ValueError("The redshift and k sampling of the linear and non-linear matter power must be the same to use the amod module")

2024-10-31 01:27 UTC, ajouellette commented
Cool! I just added the suggested changes.

2024-10-31 09:04 UTC, joezuntz approved these changes

2024-10-31 09:04 UTC, merged

2024-10-31 09:04 UTC, joezuntz commented
Thanks so much!