Code for running DES+SPT Year 3 6x2pt analysis
joezuntz/cosmosis-standard-library pull request #59
Opened 2023-03-02 20:15 UTC by ebaxter

Run the DES+SPT/Planck Y3 6x2 likelihood using cosmosis-standard-library/examples/des-y3-6x2.ini.

yaml files haven't been updated yet, but can do that as needed.

2023-03-21 14:29 UTC, joezuntz requested changes

2023-03-21 14:29 UTC, joezuntz commented on boltzmann/camb/camb_interface.py
> +    more_config['n_logz'] = options.get_int(opt, 'n_logz', default=0)
Calculating chistar seems to be so fast that it's not even an overhead for SN likelihoods. So there's probably no need to make calculating it optional.

2023-03-21 14:29 UTC, joezuntz commented on boltzmann/camb/camb_interface.py
> +    log_z = np.logspace(np.log10(more_config["zmax_background"]), np.log10(more_config['zmax_logz']), num = more_config['n_logz'])
Can use np.geomspace instead of np.logspace here to make this more readable.

2023-03-21 14:29 UTC, joezuntz commented on boltzmann/camb/camb_interface.py
> +# JMedit: new function here
This is already included in the cosmosis main branch. I think it should merge okay anyway, but if not then might want to merge main into this branch first.

2023-03-21 14:29 UTC, joezuntz commented on cmb_lensing/kappa_beam/kappa_beam.py
> +import pdb
Not needed now I think?

2023-03-21 14:29 UTC, joezuntz commented on cmb_lensing/kappa_beam/kappa_beam.py
> +        if (is_auto):
Can use some "else"s here for clarity. I usually prefer to do it this way round:
```
if is_auto:
    ...
else:
    ...
```

i.e. avoiding the "not".

2023-03-21 14:29 UTC, joezuntz commented on cmb_lensing/kappa_beam/kappa_beam.py
> +        if (block.has_value(section,"nbin")):
Can probably just do a loop here over all these parameters.

2023-03-21 14:29 UTC, joezuntz commented on cmb_lensing/kappa_ell_cut/kappa_ell_cut.py
> +import pdb
Also no longer needed I think.  BTW you can just use `breakpoint()` from py3.7 onwards with no need to import pdb.

2023-03-21 14:29 UTC, joezuntz commented on likelihood/2pt/2pt_like.py
> +        self.suffixes = suffixes
Won't this fail below if suffixes is not set?

2023-03-21 14:29 UTC, joezuntz commented on likelihood/2pt/2pt_point_mass/2pt_point_mass.py
> +        #IS THIS USED???
Probably good to check this.

2023-03-21 14:29 UTC, joezuntz commented on likelihood/2pt/spec_tools.py
> +        #Useful when we have multiple two point functions that we want to label separately
I don't really undertand this - could you add comments explaining how to use this?  Also good to remove all the commented out stuff.

2023-03-21 14:29 UTC, joezuntz commented on shear/cl_to_xi_fullsky/cl_to_xi_interface.py
> +        add = "_%s"%save_name
This is the same as `"_" + save_name` but less clear

2023-03-21 14:29 UTC, joezuntz commented on shear/cl_to_xi_fullsky/cl_to_xi_interface.py
> +        try:
Probably want to check `if isinstance(output_section, str)` here instead of a try/except.

2023-03-21 14:29 UTC, joezuntz commented on structure/magnification/add_magnification.py
> +    do_galaxy_cmbkappa = options.get_bool(option_section, "galaxy-cmbkappa", True)
Default here should be `False` I think

2023-03-21 14:29 UTC, joezuntz commented on structure/magnification/add_magnification.py
> +    elif do_galaxy_cmbkappa:
Need to change this block more widely for the messages to make sense.

2023-03-21 14:29 UTC, joezuntz commented on structure/projection/project_2d.py
> +            if ((sample_name not in self.kernels) and (sample_name != 'cmb')):
outer brackets not needed.

2023-03-21 14:29 UTC, joezuntz commented on structure/projection/projection_tools/fastpt_tools.py
> +            "sig3nl" : PXXNL_b1b2bsb3nl[8], "sig4" : PXXNL_b1b2bsb3nl[7]}
Is this a more general bug I should worry about?

2023-03-21 14:29 UTC, joezuntz commented on structure/projection/projection_tools/fastpt_tools.py
> +def get_Pk_basis_funcs(block, pt_type,
It's useful to make sure people's text editors don't automatically tidy code just because they think it's a good idea, otherwise PRs are filled with these whitespace-only changes.

2023-03-21 14:30 UTC, joezuntz commented on likelihood/2pt/2pt_like.py
> +        self.suffixes = suffixes
Yes, now the automatic checks have run we can see that this breaks the Y1 likelihood (and presumably Y3 etc)

2023-03-25 00:28 UTC, ebaxter commented on cmb_lensing/kappa_beam/kappa_beam.py
> +        if (block.has_value(section,"nbin")):
Sorry, not sure I follow.  Which parameters?

2023-03-25 00:29 UTC, ebaxter commented on cmb_lensing/kappa_ell_cut/kappa_ell_cut.py
> +import pdb
Good to know, thanks.

2023-03-25 02:14 UTC, ebaxter commented on likelihood/2pt/2pt_like.py
> +        self.suffixes = suffixes
Yes, I should have checked this.  Should be working now.

2023-03-27 11:03 UTC, joezuntz commented on cmb_lensing/kappa_beam/kappa_beam.py
> +        if (block.has_value(section,"nbin")):
Never mind, was jut being a bit too zealous here.

2023-03-27 20:08 UTC, ebaxter commented on boltzmann/camb/camb_interface.py
> +    more_config['n_logz'] = options.get_int(opt, 'n_logz', default=0)
Changed default of want_chistar to True

2023-03-30 10:41 UTC, joezuntz requested changes

2023-03-30 10:41 UTC, joezuntz commented on cmb_lensing/kappa_ell_cut/kappa_ell_cut.py
> +    shearkappa_output_section = options.get_string(option_section, "shearkappa_output_section", default=None)
Setting the default as None for these parameters means they are required and will raise an error if they're not set. I think you were aiming to make them optional here? If so I usually set the default to just `""`.

Then you might need to change the check in the apply_lcut function

2023-03-30 20:29 UTC, ebaxter commented on cmb_lensing/kappa_ell_cut/kappa_ell_cut.py
> +    shearkappa_output_section = options.get_string(option_section, "shearkappa_output_section", default=None)
Should be fixed now.

2023-04-04 11:06 UTC, joezuntz approved these changes

2023-04-04 12:09 UTC, merged