Better sampling of sigma_8
joezuntz/cosmosis-standard-library pull request #86
Opened 2023-07-10 19:43 UTC by tilmantroester

This PR replaces the janky sigma_8 sampling setup. Instead of running CAMB twice, the transfer function (which takes the most time) is only computed once and then the power spectra are recomputed using the correct A_s corresponding to the requested sigma_8.

This speeds things up by ~50% and also avoids the numerical uncertainty in the initial estimate of sigma_8 due to the low accuracy settings of the first run. Since `sigma_8_input` now agrees with the output `sigma_8`, I added the option of taking `sigma_8` as the input directly. If both `sigma_8` and `A_s` are provided, `sigma_8` takes precedence.

This approach could in principle be used to do fast sampling of all non-cosmology parameters, such as primordial power spectrum parameters in general or HMCode parameters. See for example cells 50 onward here: https://camb.readthedocs.io/en/latest/CAMBdemo.html

2023-07-11 11:01 UTC, joezuntz requested changes
One more request - could you update e.g the des-y1 ini file to use the new name. That is tested in the CI.

2023-07-11 11:01 UTC, joezuntz commented on boltzmann/camb/camb_interface.py
> +    if not block.has_value(cosmo, 'A_s'):
At this point I'd like to do some more checks to avoid silent errors.

We should check that exactly one of A_s and sigma_8 is set - any other option is asking for trouble.

2023-07-11 11:01 UTC, joezuntz commented on boltzmann/camb/camb_interface.py
> +            if (block.has_value(cosmo, 'sigma_8_input')
We should  drop the "sigma_8_input" specification in favour of sigma_8. We should check for it and reject it if it is present.

2023-07-11 12:40 UTC, tilmantroester commented on boltzmann/camb/camb_interface.py
> +            if (block.has_value(cosmo, 'sigma_8_input')
So no backwards compatibility?

2023-07-11 12:47 UTC, joezuntz commented on boltzmann/camb/camb_interface.py
> +            if (block.has_value(cosmo, 'sigma_8_input')
Good point. We should drop one of them, I guess it's clarity vs compatibility.  You're right, let's stick with compatibility and disallow sigma_8.

2023-07-11 12:50 UTC, tilmantroester commented on boltzmann/camb/camb_interface.py
> +            if (block.has_value(cosmo, 'sigma_8_input')
I was thinking more along the lines of a deprecation warning. But I don't know if there's a framework in cosmosis for that.

2023-07-11 13:12 UTC, joezuntz commented on boltzmann/camb/camb_interface.py
> +            if (block.has_value(cosmo, 'sigma_8_input')
You could do what we do with the old `massless_nu` parameter names and just print out a warning?

2023-07-12 14:32 UTC, tilmantroester commented on boltzmann/camb/camb_interface.py
> +    if not block.has_value(cosmo, 'A_s'):
Added a warning if both A_s and sigma_8 are provided.

2023-07-12 14:32 UTC, tilmantroester commented on boltzmann/camb/camb_interface.py
> +            if (block.has_value(cosmo, 'sigma_8_input')
Added a deprecation warning for sigma_8_input but allowing both for now.

2023-07-15 19:06 UTC, tilmantroester commented
Back to you!

2023-07-17 11:02 UTC, merged

2023-07-17 11:03 UTC, joezuntz commented
Brilliant, thanks for this!